-- 1. Se crea un DROP TABLE para todas las tablas:

-- Tablas hijas primero
DROP TABLE DOSIS CASCADE CONSTRAINTS;
DROP TABLE PAGO CASCADE CONSTRAINTS;
DROP TABLE RECETA CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;

-- Tablas base
DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE FORMATO_MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE VIA_ADMIN CASCADE CONSTRAINTS;
DROP TABLE INTERVALOS_CONSUMO CASCADE CONSTRAINTS;
DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS;
DROP TABLE DIAGNOSTICO CASCADE CONSTRAINTS;
DROP TABLE DIGITADOR CASCADE CONSTRAINTS;
DROP TABLE PACIENTE CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE BANCO CASCADE CONSTRAINTS;
DROP TABLE TIPOS_RECETA CASCADE CONSTRAINTS;
DROP TABLE METODO_PAGO CASCADE CONSTRAINTS;

-- CASO N°1:
-- 2. Se crean las tablas (CREATE TABLE):

CREATE TABLE MEDICAMENTO(
cod_medicamento VARCHAR2(7) NOT NULL,
nombre VARCHAR2(25) NOT NULL,
formato_medicamento CHAR(2) NOT NULL,
via_administracion CHAR(3) NOT NULL,
stock_medicamento NUMBER(6) NOT NULL
);

CREATE TABLE FORMATO_MEDICAMENTO(
formato_medicamento CHAR(2) NOT NULL,
nombre_formatoMedicamento VARCHAR2(12) UNIQUE,
tipo_medicamento VARCHAR2(12) NOT NULL
);

CREATE TABLE VIA_ADMIN(
id_viaAdmin CHAR(3) NOT NULL,
descripcion_Admin VARCHAR2(10) UNIQUE
);

CREATE TABLE DOSIS(
id_medicamento VARCHAR2(7) NOT NULL,
id_receta NUMBER(7) NOT NULL,
cantidad_medicamentos NUMERIC(2) NOT NULL,
dias_consumo NUMERIC(2) NOT NULL,
id_intervaloConsumo CHAR(1) NOT NULL,
descrpcion_dosis VARCHAR2(25) NOT NULL
);

CREATE TABLE INTERVALOS_CONSUMO(
id_intervaloConsumo CHAR(1) NOT NULL,
tiempo_intervalo VARCHAR2(20) UNIQUE
);

CREATE TABLE RECETA(
cod_receta NUMERIC(7) NOT NULL,
observaciones_RECETA VARCHAR2(50) NOT NULL,
fecha_emision DATE NOT NULL,
fecha_vencimiento DATE NOT NULL,
id_digitador NUMERIC(4) NOT NULL,
id_paciente NUMERIC(8) NOT NULL,
id_medico CHAR (6) NOT NULL,
id_tipoReceta CHAR(1) NOT NULL,
id_medicamento VARCHAR2(7) NOT NULL,
id_diagnostico CHAR(3) NOT NULL
);

CREATE TABLE TIPOS_RECETA(
id_tipoReceta CHAR (1) NOT NULL,
tipo_receta VARCHAR2(11) NOT NULL
);

CREATE TABLE MEDICO(
id_medico CHAR(6) NOT NULL,
rut_medico NUMERIC(8) UNIQUE,
dv_medico CHAR(1),
primer_nombre VARCHAR2(25) NOT NULL,
segundo_nombre VARCHAR2(25),
primer_apellido VARCHAR2(25) NOT NULL,
segundo_apellido VARCHAR2(25) NOT NULL,
telefono_medico VARCHAR(12) UNIQUE,
especialidad NUMBER(1) NOT NULL
);

CREATE TABLE ESPECIALIDAD(
id_especialidad NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
nombre_especialidad VARCHAR(25) UNIQUE
);

CREATE TABLE DIAGNOSTICO(
cod_diagnostico CHAR(3) NOT NULL,
tipo_diagnostico VARCHAR2(30) UNIQUE,
observaciones_diagnostico VARCHAR2(50) NOT NULL
);

CREATE TABLE DIGITADOR(
id_digitador NUMERIC(4) NOT NULL,
dni_digitador NUMERIC(20) UNIQUE,
dv_digitador CHAR(1),
primer_nombre VARCHAR2(25) NOT NULL,
segundo_nombre VARCHAR2(25),
primer_apellido VARCHAR2(25) NOT NULL,
segundo_apellido VARCHAR2(25) NOT NULL
);

CREATE TABLE PACIENTE(
rut_paciente NUMERIC(8) NOT NULL,
dv_paciente CHAR(1),
primer_nombre VARCHAR2(25) NOT NULL,
segundo_nombre VARCHAR2(25),
primer_apellido VARCHAR2(25) NOT NULL,
segundo_apellido VARCHAR2(25) NOT NULL,
edad_paciente NUMERIC(2) NOT NULL,
fecha_nacimiento DATE NOT NULL,
telefono_paciente VARCHAR2(12) NOT NULL,
calle_paciente VARCHAR2(25) NOT NULL,
numero_calle VARCHAR2(6) NOT NULL,
comuna_paciente NUMBER(4) NOT NULL,
ciudad_paciente CHAR(3) NOT NULL,
region_paciente CHAR(5) NOT NULL
);

CREATE TABLE COMUNA(
id_comuna NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1101 INCREMENT BY 1),
nombre_comuna VARCHAR2(25) UNIQUE,
ciudad CHAR(3) NOT NULL
);

CREATE TABLE CIUDAD(
id_ciudad CHAR(3) NOT NULL,
nombre_ciudad VARCHAR2(25) UNIQUE,
region CHAR(5) NOT NULL
);

CREATE TABLE REGION(
id_region CHAR(5) NOT NULL,
nombre_region VARCHAR2(25) UNIQUE
);

CREATE TABLE BANCO(
cod_banco CHAR(2) NOT NULL,
nombre_banco VARCHAR2(25) NOT NULL
);

CREATE TABLE PAGO(
cod_boleta NUMERIC(6) NOT NULL,
id_receta NUMERIC (7) NOT NULL,
fecha_pago DATE NOT NULL,
monto_total NUMERIC (10) NOT NULL,
id_metodo_pago CHAR(1) NOT NULL,
id_banco CHAR(2) NOT NULL
);

-- 3. Se establece la relación de claves primarias y foráneas:

-- PK para la tabla RECETA:
ALTER TABLE RECETA
ADD CONSTRAINT pk_receta PRIMARY KEY (cod_receta);

-- PK para la tabla DIGITADOR:
ALTER TABLE DIGITADOR
ADD CONSTRAINT pk_digitador PRIMARY KEY (id_digitador);

-- PK para la tabla PAGO:
ALTER TABLE PAGO
ADD CONSTRAINT pk_pago PRIMARY KEY (cod_boleta);

-- PK para la tabla MEDICAMENTO:
ALTER TABLE MEDICAMENTO
ADD CONSTRAINT pk_medicamento PRIMARY KEY (cod_medicamento);

-- PK para la tabla FORMATO_MEDICAMENTO:
ALTER TABLE FORMATO_MEDICAMENTO
ADD CONSTRAINT pk_formato_medicamento PRIMARY KEY (formato_medicamento);

-- PK para la tabla VIA_ADMIN:
ALTER TABLE VIA_ADMIN
ADD CONSTRAINT pk_via_admin PRIMARY KEY (id_viaAdmin);

-- PK para la tabla DOSIS:
ALTER TABLE DOSIS
ADD CONSTRAINT pk_dosis PRIMARY KEY (id_receta, id_medicamento);

-- PK para la tabla INTERVALO_CONSUMO:
ALTER TABLE INTERVALOS_CONSUMO
ADD CONSTRAINT pk_intervalo PRIMARY KEY (id_intervaloConsumo);

-- PK para la tabla TIPOS_RECETA:
ALTER TABLE TIPOS_RECETA
ADD CONSTRAINT pk_tiposReceta PRIMARY KEY (id_tipoReceta);

-- PK para la tabla MEDICO:
ALTER TABLE MEDICO
ADD CONSTRAINT pk_medico PRIMARY KEY (id_medico);

-- PK para la tabla ESPECIALIDAD:
ALTER TABLE ESPECIALIDAD
ADD CONSTRAINT pk_especialidad PRIMARY KEY (id_especialidad);

-- PK para la tabla DIAGNOSTICO:
ALTER TABLE DIAGNOSTICO
ADD CONSTRAINT pk_diagnostico PRIMARY KEY (cod_diagnostico);

-- PK para la tabla PACIENTE:
ALTER TABLE PACIENTE
ADD CONSTRAINT pk_paciente PRIMARY KEY (rut_paciente);

-- PK para la tabla COMUNA:
ALTER TABLE COMUNA
ADD CONSTRAINT pk_comuna PRIMARY KEY (id_comuna);

-- PK para la tabla CIUDAD:
ALTER TABLE CIUDAD
ADD CONSTRAINT pk_ciudad PRIMARY KEY (id_ciudad);

-- PK para la tabla REGION:
ALTER TABLE REGION
ADD CONSTRAINT pk_region PRIMARY KEY (id_region);

-- PK para la tabla BANCO:
ALTER TABLE BANCO
ADD CONSTRAINT pk_banco PRIMARY KEY (cod_banco);

-- SE añaden las relaciones entre tablas:

-- Se añade la FK DIGITADOR a TABLA RECETA
ALTER TABLE RECETA
ADD CONSTRAINT FK_DIGITADOR_RECETA
FOREIGN KEY (id_digitador)
REFERENCES DIGITADOR(id_digitador);

-- Se añade una PF a la tabla DOSIS
ALTER TABLE DOSIS
ADD CONSTRAINT fk_dosis_medicamento
FOREIGN KEY (id_medicamento)
REFERENCES MEDICAMENTO(cod_medicamento);

ALTER TABLE DOSIS
ADD CONSTRAINT fk_dosis_receta
FOREIGN KEY (id_receta)
REFERENCES RECETA (cod_receta);

-- Se añade la FK RECETA a TABLA PAGO.
ALTER TABLE PAGO
ADD CONSTRAINT fk_cod_receta
FOREIGN KEY (id_receta)
REFERENCES RECETA (cod_receta);

-- Se añade la FK DIAGNOSTICO a TABLA RECETA
ALTER TABLE RECETA
ADD CONSTRAINT fk_diagnostico
FOREIGN KEY (id_diagnostico)
REFERENCES DIAGNOSTICO (cod_diagnostico);

-- Se añade la FK PACIENTE a TABLA RECETA
ALTER TABLE RECETA
ADD CONSTRAINT fk_paciente
FOREIGN KEY (id_paciente)
REFERENCES PACIENTE (rut_paciente);

-- Se añade la FK MEDICO a TABLA RECETA
ALTER TABLE RECETA
ADD CONSTRAINT fk_medico
FOREIGN KEY (id_medico)
REFERENCES MEDICO (id_medico);

-- Se añade la FK MEDICAMENTO a TABLA RECETA
ALTER TABLE RECETA
ADD CONSTRAINT fk_medicamento
FOREIGN KEY (id_medicamento)
REFERENCES MEDICAMENTO (cod_medicamento);

-- Se añade la FK TIPOS_RECETA a TABLA RECETA
ALTER TABLE RECETA
ADD CONSTRAINT fk_tiposReceta
FOREIGN KEY (id_tipoReceta)
REFERENCES TIPOS_RECETA (id_tipoReceta);

-- Se añade la FK BANCO a TABLA PAGO
ALTER TABLE PAGO
ADD CONSTRAINT fk_banco
FOREIGN KEY (id_banco)
REFERENCES BANCO (cod_banco);

-- Se añade la FK FORMATO_MEDICAMENTO a TABLA MEDICAMENTO
ALTER TABLE MEDICAMENTO
ADD CONSTRAINT fk_formato_medicamento
FOREIGN KEY (formato_medicamento)
REFERENCES FORMATO_MEDICAMENTO (formato_medicamento);

-- Se añade la FK VIA ADMINISTRACION a TABLA MEDICAMENTO
ALTER TABLE MEDICAMENTO
ADD CONSTRAINT fk_via_Admin
FOREIGN KEY (via_administracion)
REFERENCES VIA_ADMIN (id_viaAdmin);

-- Se añade la FK INTERVALO_CONSUMO a TABLA DOSIS
ALTER TABLE DOSIS
ADD CONSTRAINT fk_intervalo_consumo
FOREIGN KEY (id_intervaloConsumo)
REFERENCES INTERVALOS_CONSUMO (id_intervaloConsumo);

-- Se añade la FK ESPECIALIDAD a TABLA MEDICO
ALTER TABLE MEDICO
ADD CONSTRAINT fk_especialidad
FOREIGN KEY (especialidad)
REFERENCES ESPECIALIDAD (id_especialidad);

-- Se añade la FK REGION a TABLA CIUDAD
ALTER TABLE CIUDAD
ADD CONSTRAINT fk_region
FOREIGN KEY (region)
REFERENCES REGION (id_region);

-- Se añade la FK CIUDAD a TABLA COMUNA
ALTER TABLE COMUNA
ADD CONSTRAINT fk_ciudad
FOREIGN KEY (ciudad)
REFERENCES CIUDAD (id_ciudad);

ALTER TABLE PACIENTE
ADD CONSTRAINT fk_comunaPaciente
    FOREIGN KEY (comuna_paciente)
    REFERENCES COMUNA (id_comuna)
ADD CONSTRAINT fk_ciudadPeciente
    FOREIGN KEY (ciudad_paciente)
    REFERENCES CIUDAD (id_ciudad)
ADD CONSTRAINT fk_regionPaciente
    FOREIGN KEY (region_paciente)
    REFERENCES REGION (id_region);
    
-- CASO N°2
-- 3 - Se modifican reglas de negocio:

-- Se añade precio unitario a la TABLA MEDICAMENTO.
ALTER TABLE MEDICAMENTO
ADD precio_unitario NUMBER(10,2);

-- Se añade una condición que especifica rangos de precios de los medicamentos.
ALTER TABLE MEDICAMENTO
ADD CONSTRAINT chk_precio_medicamento
CHECK (precio_unitario BETWEEN 1000 and 2000000);

-- Se añade una nueva tabla llamada MEDIOS_PAGO que se asociará con la tabla pagos
CREATE TABLE METODO_PAGO(
id_metodoPago CHAR(1),
nombre_metodoPago VARCHAR2(13)
);

ALTER TABLE METODO_PAGO
ADD CONSTRAINT pk_metodopago PRIMARY KEY (id_metodoPago);


ALTER TABLE PAGO
ADD CONSTRAINT fk_medioPago_pago
FOREIGN KEY (id_metodo_pago)
REFERENCES METODO_PAGO (id_metodoPago);

-- Se elimina la columna EDAD_PACIENTE de la TABLA PACIENTE.
ALTER TABLE PACIENTE
DROP COLUMN edad_paciente;
